// Diesel schema — this file would normally be auto-generated by `diesel print-schema`.
// It is provided here as a scaffold matching the migration.

diesel::table! {
    facilities (id) {
        id -> Uuid,
        name -> Varchar,
        address -> Text,
    }
}

diesel::table! {
    users (id) {
        id -> Uuid,
        username -> Varchar,
        password_hash -> Text,
        role -> Text,
        facility_id -> Nullable<Uuid>,
        totp_secret -> Nullable<Bytea>,
        mfa_enabled -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    sessions (id) {
        id -> Uuid,
        user_id -> Uuid,
        token_hash -> Text,
        expires_at -> Timestamptz,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    csrf_tokens (id) {
        id -> Uuid,
        session_id -> Uuid,
        token_hash -> Text,
        expires_at -> Timestamptz,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    resources (id) {
        id -> Uuid,
        title -> Varchar,
        category -> Nullable<Varchar>,
        tags -> Jsonb,
        hours -> Jsonb,
        pricing -> Jsonb,
        contact_info_encrypted -> Nullable<Bytea>,
        media_refs -> Jsonb,
        address -> Nullable<Text>,
        latitude -> Nullable<Float8>,
        longitude -> Nullable<Float8>,
        state -> Text,
        scheduled_publish_at -> Nullable<Timestamptz>,
        current_version -> Int4,
        created_by -> Uuid,
        facility_id -> Nullable<Uuid>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    resource_versions (id) {
        id -> Uuid,
        resource_id -> Uuid,
        version_number -> Int4,
        snapshot -> Jsonb,
        changed_by -> Uuid,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    lodgings (id) {
        id -> Uuid,
        name -> Varchar,
        description -> Nullable<Text>,
        state -> Text,
        amenities -> Jsonb,
        facility_id -> Nullable<Uuid>,
        deposit_amount -> Nullable<Numeric>,
        monthly_rent -> Nullable<Numeric>,
        deposit_cap_validated -> Bool,
        created_by -> Uuid,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    lodging_periods (id) {
        id -> Uuid,
        lodging_id -> Uuid,
        start_date -> Date,
        end_date -> Date,
        min_nights -> Int4,
        max_nights -> Int4,
        vacancy -> Bool,
    }
}

diesel::table! {
    lodging_rent_changes (id) {
        id -> Uuid,
        lodging_id -> Uuid,
        proposed_rent -> Numeric,
        proposed_deposit -> Numeric,
        status -> Text,
        requested_by -> Uuid,
        reviewed_by -> Nullable<Uuid>,
        reviewed_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    warehouses (id) {
        id -> Uuid,
        facility_id -> Uuid,
        name -> Varchar,
    }
}

diesel::table! {
    bins (id) {
        id -> Uuid,
        warehouse_id -> Uuid,
        label -> Varchar,
    }
}

diesel::table! {
    inventory_lots (id) {
        id -> Uuid,
        facility_id -> Uuid,
        warehouse_id -> Uuid,
        bin_id -> Uuid,
        item_name -> Varchar,
        lot_number -> Varchar,
        quantity_on_hand -> Int4,
        quantity_reserved -> Int4,
        expiration_date -> Nullable<Date>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    inventory_transactions (id) {
        id -> Uuid,
        lot_id -> Uuid,
        direction -> Text,
        quantity -> Int4,
        reason -> Nullable<Text>,
        performed_by -> Uuid,
        created_at -> Timestamptz,
        is_immutable -> Bool,
    }
}

diesel::table! {
    media_files (id) {
        id -> Uuid,
        original_name -> Varchar,
        stored_path -> Text,
        mime_type -> Varchar,
        size_bytes -> Int8,
        checksum_sha256 -> Varchar,
        uploaded_by -> Uuid,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    review_decisions (id) {
        id -> Uuid,
        entity_type -> Varchar,
        entity_id -> Uuid,
        decision -> Text,
        comment -> Nullable<Text>,
        decided_by -> Uuid,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    import_jobs (id) {
        id -> Uuid,
        job_type -> Varchar,
        file_path -> Text,
        total_rows -> Int4,
        processed_rows -> Int4,
        progress_percent -> Int2,
        status -> Text,
        retries -> Int4,
        max_retries -> Int4,
        failure_log -> Nullable<Text>,
        staging_table_name -> Nullable<Varchar>,
        committed -> Bool,
        created_by -> Uuid,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    idempotency_keys (id) {
        id -> Uuid,
        key_value -> Varchar,
        entity_type -> Varchar,
        entity_id -> Uuid,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    api_connector_logs (id) {
        id -> Uuid,
        direction -> Varchar,
        endpoint -> Text,
        nonce -> Nullable<Varchar>,
        timestamp_sent -> Nullable<Timestamptz>,
        payload_hash -> Nullable<Varchar>,
        status -> Varchar,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    config_parameters (id) {
        id -> Uuid,
        profile -> Varchar,
        key -> Varchar,
        value -> Text,
        feature_switch -> Bool,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    audit_log (id) {
        id -> Uuid,
        actor_id -> Nullable<Uuid>,
        action -> Varchar,
        entity_type -> Varchar,
        entity_id -> Nullable<Uuid>,
        detail -> Nullable<Jsonb>,
        ip_address -> Nullable<Varchar>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    export_approvals (id) {
        id -> Uuid,
        export_type -> Varchar,
        requested_by -> Uuid,
        approved_by -> Nullable<Uuid>,
        watermark_text -> Nullable<Text>,
        status -> Text,
        created_at -> Timestamptz,
    }
}

// ── Join / FK relationships ──

diesel::joinable!(users -> facilities (facility_id));
diesel::joinable!(sessions -> users (user_id));
diesel::joinable!(csrf_tokens -> sessions (session_id));
diesel::joinable!(resources -> users (created_by));
diesel::joinable!(resource_versions -> resources (resource_id));
diesel::joinable!(lodgings -> facilities (facility_id));
diesel::joinable!(lodging_periods -> lodgings (lodging_id));
diesel::joinable!(lodging_rent_changes -> lodgings (lodging_id));
diesel::joinable!(warehouses -> facilities (facility_id));
diesel::joinable!(bins -> warehouses (warehouse_id));
diesel::joinable!(inventory_lots -> bins (bin_id));
diesel::joinable!(inventory_transactions -> inventory_lots (lot_id));
diesel::joinable!(import_jobs -> users (created_by));

diesel::allow_tables_to_appear_in_same_query!(
    facilities,
    users,
    sessions,
    csrf_tokens,
    resources,
    resource_versions,
    lodgings,
    lodging_periods,
    lodging_rent_changes,
    warehouses,
    bins,
    inventory_lots,
    inventory_transactions,
    media_files,
    review_decisions,
    import_jobs,
    idempotency_keys,
    api_connector_logs,
    config_parameters,
    audit_log,
    export_approvals,
);
